#!/usr/bin/env bash

#check the number of arguments
if [ "$#" -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
    fi

# Assign arguments to variables
    PATH_TO_FILE="$1"
    IP="$2"
    USERNAME="$3"
    PATH_TO_SSH_KEY="$4"

# Use scp to transfer the file to the server
    scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP":~/

# Check the exit status of the scp command
    if [ "$?" -eq 0 ]; then
      echo "File transferred successfully."
      else
        echo "File transfer failed."
      fi

