#!/bin/bash
file /tmp/iamafile 2>&1 | awk '{print "[Got]\n" $0 "\n\n[Expected]\n/tmp/iamafile: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=a6cb40078351e05121d46daa768e271846d5cc54, for GNU/Linux 3.2.0, stripped\n\n(218 chars long)"}'
